const Products = [
    {
        name: "Loofer 1",
        image: '/loofer.png',
        category: "Loofers", 
        color: "white",
        size: "large",  
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Loofer 2",
        image: '/loofer.png',
        category: "Loofers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Loofer 3",
        image: '/loofer.png',
        category: "Loofers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Loofer 4",
        image: '/loofer.png',
        category: "Loofers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Loofer 5",
        image: '/loofer.png',
        category: "Loofers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Loofer 6",
        image: '/loofer.png',
        category: "Loofers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Snicker 1",
        image: 'snicker.png',
        category: "Snickers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Snicker 2",
        image: 'snicker.png',
        category: "Snickers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Snicker 3",
        image: 'snicker.png',
        category: "Snickers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Snicker 4",
        image: 'snicker.png',
        category: "Snickers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Snicker 5",
        image: 'snicker.png',
        category: "Snickers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Snicker 6",
        image: 'snicker.png',
        category: "Snickers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Boots 1",
        image: 'boot.png',
        category: "Boots",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Boots 2",
        image: 'boot.png',
        category: "Boots",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Boots 3",
        image: 'boot.png',
        category: "Boots",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Boots 4",
        image: 'boot.png',
        category: "Boots",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Boots 5",
        image: 'boot.png',
        category: "Boots",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Boots 6",
        image: 'boot.png',
        category: "Boots",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Loofer 1",
        image: '/loofer.png',
        category: "Loofers", 
        color: "white",
        size: "large",  
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Loofer 2",
        image: '/loofer.png',
        category: "Loofers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Loofer 3",
        image: '/loofer.png',
        category: "Loofers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Loofer 4",
        image: '/loofer.png',
        category: "Loofers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Loofer 5",
        image: '/loofer.png',
        category: "Loofers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Loofer 6",
        image: '/loofer.png',
        category: "Loofers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Snicker 1",
        image: 'snicker.png',
        category: "Snickers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Snicker 2",
        image: 'snicker.png',
        category: "Snickers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Snicker 3",
        image: 'snicker.png',
        category: "Snickers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Snicker 4",
        image: 'snicker.png',
        category: "Snickers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Snicker 5",
        image: 'snicker.png',
        category: "Snickers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Snicker 6",
        image: 'snicker.png',
        category: "Snickers",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Boots 1",
        image: 'boot.png',
        category: "Boots",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Boots 2",
        image: 'boot.png',
        category: "Boots",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Boots 3",
        image: 'boot.png',
        category: "Boots",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Boots 4",
        image: 'boot.png',
        category: "Boots",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Boots 5",
        image: 'boot.png',
        category: "Boots",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
    {
        name: "Boots 6",
        image: 'boot.png',
        category: "Boots",
        color: "white",
        size: "large",
        price: "$25",
        description: 'Hello, the description of this product is displayed here',
    },
];
module.exports = Products